AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My security group for my EC2 instance
      VpcId: vpc-01236f61fd7e8a280

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07caf9f60dd9b55bb
      InstanceType: t2.micro
      SubnetId: subnet-0936cfc53606d4989
      SecurityGroupIds:
        - !Ref SecurityGroup

Outputs:
  InstancePublicIp:
    Description: The public IP address of the instance
    Value: !GetAtt Instance.PublicIp
